### ISSUE TITLE
Build for Linux ?

### ISSUE THREAD

**Issue by august0815** [aneilmac/nornpulse#1]
Hello,  
is a build for linux possible?

Thank you

"failed build on linux even for windows :

linux terminal :

error: linker `link.exe` not found
  |
  = note: No such file or directory (os error 2)

note: the msvc targets depend on the msvc linker but `link.exe` was not found

note: please ensure that Visual Studio 2017 or later, or Build Tools for Visual Studio were installed with the Visual C++ option.

note: VS Code is a different product, and is not sufficient.

warning: `nornpulse` (lib) generated 35 warnings
error: could not compile `nornpulse` (lib) due to 1 previous error; 35 warnings emitted "

**Comment by aneilmac** [comment]
Not possible without some major rework, I'm afraid. Calls are tied to specific addresses within the compiled executable.
